workflow: Data Workflow {
    user: User {
        shape: person
    }

    input: Input {
        shape: document
    }

    validation: Data Validation {
        shape: square
    }

    new: New Data? {
        shape: diamond
    }

    store: Database {
        shape: Cylinder
    }

    user -> input
    input -> validation: To Validation Engine {
        style: {
            stroke-dash: 8
            stroke: blue
            animated: true
        }
    }
    validation -> new: Valid {
        style: {
            stroke-dash: 8
            stroke: green
            animated: true
        }
    }

    validation -> user: Invalid Error Message {
        style: {
            stroke-dash: 8
            stroke: red
            animated: true
        }
    }
    new -> store: Insert {
        style: {
            stroke-dash: 8
            stroke: blue
            animated: true
        }
    }

    new <-> store: Update {
        style: {
            stroke-dash: 8
            stroke: blue
            animated: true
        }
    }

}
