one: "One" {
    shape: rectangle
    style.fill: "bisque"
    style.stroke: "#fff"
}

two: "Two" {
    shape: oval
    style.fill: "beige"
    style.stroke: "#fff"
}

three: "Three" {
    shape: circle
    style.fill: "antiquewhite"
    style.stroke: "#fff"
}

four: "Four" {
    shape: circle
    style.fill: "azure"
    style.stroke: "#fff"
}

five: "Five" {
    shape: circle
    style.fill: "darkseagreen"
    style.stroke: "#fff"
}

one -> two {
  style.stroke: "gold"
}
two -> three {
  style.stroke: "firebrick"
}
two -> four {
  style.stroke: "firebrick"
}
two -> five {
  style.stroke: "firebrick"
}
