changequote(!<,>!)
# Example 5

This graphviz graph is somewhat special, the `.dot` file is generated by Hashicorp Terraform, specifically the `terraform graph` subcommand that produces a graphviz file in the `dot` format.

## Instructions

## Mac
1. `brew install graphviz`
2. `make build`
3. `brew tap hashicorp/tap`
4. `brew install hashicorp/tap/terraform`

## Windows
1. `choco install graphviz`
2. `choco install make`
3. `choco install terraform`
4. `make build`

## Linux
The world is your oyster, do what you like.
1. `make build`

These instructions will turn this simple Terraform HCL file:

```
esyscmd( cat main.tf )
```
Into this `dot` file:

```
esyscmd( cat example_05.dot )
```

And finally Into this SVG:

![example_05](./img/example_05.svg)

changequote(`')dnl
